version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - sqlclosecheck
    - errorlint
    - nilerr
    - prealloc
    - unconvert
    - unparam
  disable:
    - gocyclo
    - funlen
    - gocognit

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
